### PR TITLE
Add nextRound and generateDailyDoublePosition for Round class

### PR DESCRIPTION
**Pull request by baldm0mma**
Co-authored-by: Hindreen Fawzi <hndfaw@gmail.com>
Co-authored-by: DeMarcus Kirby <tkd024@gmail.com>
Co-authored-by: Jev Forsberg <jev.forsberg@gmail.com>

### CODE REVIEW

**Comment by baldm0mma** [comment]
@KirbyDD @hndfaw nextRound counter and generateDailyDoublePosition methods ready for use.

**Review by KirbyDD — APPROVED** [review]
interesting. can you kind of explain your approach with how you are going to use the dailyDouble method

**Comment by hndfaw** [comment]
Thanks @baldm0mma! let's discuss how dailyDouble works this afternoon before we move on with this merge, it's still confusing me ;)

**Comment by baldm0mma** [comment]
@hndfaw @KirbyDD everything's set up class-side for the daily double. Just waiting to chat about what it will look like on the DOM. Please check this code, if it makes sense, push when ready. :)

**Pull request merged**
